package sm.gui.iu;

import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.image.BufferedImage;

/**
 *
 * @author guillesiesta
 */
public class Lienzo2DImagen extends Lienzo2D {

    private BufferedImage imagen;
    /**
     * Creates new form Lienzo2DImagen
     */
    public Lienzo2DImagen() {
        initComponents();
    }

    public void setImage(BufferedImage img){
        this.imagen = img;
        if(img!=null) {
        setPreferredSize(new Dimension(img.getWidth(),img.getHeight()));
}

    }

    public BufferedImage getImage(){
        return imagen;
    }
    
    @Override
    public void paintComponent(Graphics g){
        super.paintComponent(g);
        if(imagen!=null)   g.drawImage(imagen,0,0,this);
        
    }


    public BufferedImage getImage(boolean drawVector){
        if (drawVector) {
            BufferedImage imagenAux = new BufferedImage(imagen.getWidth(),imagen.getHeight(),imagen.getType());
            Graphics2D g2d = imagenAux.createGraphics();
            this.paint(g2d);
            
            return imagenAux;
            
        }else{
            
        return getImage();
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(206, 204, 204));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
